pipeline{
    agent any
    environment {
        ENV_TAG = "dev"
        WEEE_APP = "pipeline-demo1"
    }
    parameters {
        gitParameter branchFilter: 'origin/(.*)',
            defaultValue: 'master',
            name: 'VERSION',
            type: 'PT_BRANCH',
            sortMode: 'DESCENDING_SMART',
            useRepository: "https://github.com/GacuiSayweee/gacui-ops-cicd.git"
        virtualEnv name: 'VIRTUAL_ENV_TAG', baseTag: 'dev'
    }
    stages {
        stage('Deploy') {
            steps{
                script {
                    def concatenatedString = deploymentEnhance(appname: "${env.WEEE_APP}")
                    echo "select branch is ${params.VIRTUAL_ENV_TAG}"
//                     echo "select check is ${params.CHECK}"
                }
                deploymentEnhance appname: env.WEEE_APP
                echo 'Hello World'
            }
        }
    }
}
